* merged r12637 (sdl driver output), r12638 (status message), r12639 (macos scripts), r12640 (configure), r12641, r12642, r12643 (macos updates), r12646 (new textures), r12648 (new alien death sound), r12649, r12650 (two new textures), r12651 (wrong menuText pointer), r12652 (fixed assert in AIR_AircraftReturnToBase) and r12653 (fixed bullet related assert, breaks savegames [sorry], fixed geoscape info box overlapping) from trunk to 2.2 branch

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2121,7 +2121,6 @@ fi
 #---------------------------------------------------------------------------------------------
 # CHECK TARGET_OS
 #---------------------------------------------------------------------------------------------
-
 { echo "$as_me:$LINENO: checking target OS" >&5
 echo $ECHO_N "checking target OS... $ECHO_C" >&6; }
 if test `echo $target_os | sed "s/\(linux\).*/\1/"` = "linux"
@@ -2150,6 +2149,43 @@ then
 
 	CFLAGS="$CFLAGS -F$with_opengl_framework"
 	LDFLAGS="$LDFLAGS -framework IOKit -framework Foundation -framework OpenGL"
+	# fix this darn SDL stuff....
+	if test -d /Library/Frameworks/SDL.framework
+	then
+		sdl_mac_cflags="$sdl_mac_cflags -I/Library/Frameworks/SDL.framework/Headers"
+		sdl_mac_ldflags="$sdl_mac_ldflags -framework SDL"
+	else
+		# should test for different framework locations, like /System/Library/Frameworks
+		# and ~/Library/Frameworks..... later....
+		{ { echo "$as_me:$LINENO: error: Could not find SDL Framework at /Library/Frameworks." >&5
+echo "$as_me: error: Could not find SDL Framework at /Library/Frameworks." >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+	if test -d /Library/Frameworks/SDL_mixer.framework
+	then
+		sdl_mac_cflags="$sdl_mac_cflags -I/Library/Frameworks/SDL_mixer.framework/Headers"
+		sdl_mac_ldflags="$sdl_mac_ldflags -framework SDL_mixer"
+	else
+		{ { echo "$as_me:$LINENO: error: Could not find SDL_mixer Framework at /Library/Frameworks." >&5
+echo "$as_me: error: Could not find SDL_mixer Framework at /Library/Frameworks." >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+	if test -d /Library/Frameworks/SDL_ttf.framework
+	then
+		sdl_mac_cflags="$sdl_mac_cflags -I/Library/Frameworks/SDL_ttf.framework/Headers"
+		sdl_mac_ldflags="$sdl_mac_ldflags -framework SDL_ttf"
+	else
+		{ { echo "$as_me:$LINENO: error: Could not find SDL_ttf Framework at /Library/Frameworks." >&5
+echo "$as_me: error: Could not find SDL_ttf Framework at /Library/Frameworks." >&2;}
+   { (exit 1); exit 1; }; }
+	fi
+	### most mac users will have their additional libs and headers under /opt/local,
+	### check for that, and if present, add to CFLAGS/LDFLAGS (really convenient!)
+	if test -d /opt/local
+	then
+		CFLAGS="$CFLAGS -I/opt/local/include"
+		LDFLAGS="$LDFLAGS -L/opt/local/lib"
+	fi
 else
 	{ { echo "$as_me:$LINENO: error: The target operating system '$target_os' is unknown, please contact the developers" >&5
 echo "$as_me: error: The target operating system '$target_os' is unknown, please contact the developers" >&2;}
@@ -7926,6 +7962,7 @@ echo "$as_me: error: Could not find internationalization library with gettext in
 	sdl_config=$with_sdl_config
 
 	OLD_CPPFLAGS=$CPPFLAGS
+	OLD_CFLAGS=$CFLAGS
 	OLD_LDFLAGS=$LDFLAGS
 
 	# Extract the first word of "$sdl_config", so it can be a program name with args.
@@ -7976,6 +8013,14 @@ fi
 	else
 		{ echo "$as_me:$LINENO: WARNING: cannot find $sdl_config might fail to find SDL!" >&5
 echo "$as_me: WARNING: cannot find $sdl_config might fail to find SDL!" >&2;}
+		if test $TARGET_OS = "darwin"
+		then
+			# mac is special...again
+			CFLAGS="$CFLAGS $sdl_mac_cflags"
+			LDFLAGS="$LDFLAGS $sdl_mac_ldflags"
+			SDL_CFLAGS="$sdl_mac_cflags"
+			SDL_LIBS="$sdl_mac_ldflags"
+		fi
 	fi
 
 	#---------------------------------------------------------------------------------------------
@@ -8133,7 +8178,11 @@ echo "$as_me: error: You must have the SDL development headers" >&2;}
 	#---------------------------------------------------------------------------------------------
 	# multiple main functions error for SDL_mixer and SDL_ttf otherwise
 	# problem might be that -L<SDL_dir> might be missing then
-	LDFLAGS=$OLD_LDFLAGS
+	# (no issue at mac)
+	if test $TARGET_OS != "darwin"
+	then
+		LDFLAGS=$OLD_LDFLAGS
+	fi
 
 
 for ac_header in SDL_mixer.h
@@ -8281,14 +8330,12 @@ done
 echo "$as_me: error: You must have the SDL_mixer development headers" >&2;}
    { (exit 1); exit 1; }; }
 	fi
-
-{ echo "$as_me:$LINENO: checking for Mix_OpenAudio in -lSDL_mixer" >&5
-echo $ECHO_N "checking for Mix_OpenAudio in -lSDL_mixer... $ECHO_C" >&6; }
-if test "${ac_cv_lib_SDL_mixer_Mix_OpenAudio+set}" = set; then
+	{ echo "$as_me:$LINENO: checking for library containing Mix_OpenAudio" >&5
+echo $ECHO_N "checking for library containing Mix_OpenAudio... $ECHO_C" >&6; }
+if test "${ac_cv_search_Mix_OpenAudio+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lSDL_mixer  $LIBS"
+  ac_func_search_save_LIBS=$LIBS
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -8311,7 +8358,14 @@ return Mix_OpenAudio ();
   return 0;
 }
 _ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
+for ac_lib in '' SDL_mixer; do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+  fi
+  rm -f conftest.$ac_objext conftest$ac_exeext
 if { (ac_try="$ac_link"
 case "(($ac_try" in
   *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
@@ -8329,34 +8383,42 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_SDL_mixer_Mix_OpenAudio=yes
+  ac_cv_search_Mix_OpenAudio=$ac_res
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_SDL_mixer_Mix_OpenAudio=no
+
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
+      conftest$ac_exeext
+  if test "${ac_cv_search_Mix_OpenAudio+set}" = set; then
+  break
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_SDL_mixer_Mix_OpenAudio" >&5
-echo "${ECHO_T}$ac_cv_lib_SDL_mixer_Mix_OpenAudio" >&6; }
-if test $ac_cv_lib_SDL_mixer_Mix_OpenAudio = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBSDL_MIXER 1
-_ACEOF
-
-  LIBS="-lSDL_mixer $LIBS"
-
+done
+if test "${ac_cv_search_Mix_OpenAudio+set}" = set; then
+  :
 else
-  { { echo "$as_me:$LINENO: error: You must have SDL_mixer!!!" >&5
-echo "$as_me: error: You must have SDL_mixer!!!" >&2;}
-   { (exit 1); exit 1; }; }
+  ac_cv_search_Mix_OpenAudio=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_search_Mix_OpenAudio" >&5
+echo "${ECHO_T}$ac_cv_search_Mix_OpenAudio" >&6; }
+ac_res=$ac_cv_search_Mix_OpenAudio
+if test "$ac_res" != no; then
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+
 fi
 
-
+	if test "$ac_cv_search_Mix_OpenAudio" = "no"
+	then
+		{ { echo "$as_me:$LINENO: error: You must have the SDL_mixer development libraries" >&5
+echo "$as_me: error: You must have the SDL_mixer development libraries" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
 	#---------------------------------------------------------------------------------------------
 	# Check for SDL_ttf
 	#---------------------------------------------------------------------------------------------
@@ -8507,14 +8569,12 @@ done
 echo "$as_me: error: You must have the SDL_ttf development headers" >&2;}
    { (exit 1); exit 1; }; }
 	fi
-
-{ echo "$as_me:$LINENO: checking for TTF_Init in -lSDL_ttf" >&5
-echo $ECHO_N "checking for TTF_Init in -lSDL_ttf... $ECHO_C" >&6; }
-if test "${ac_cv_lib_SDL_ttf_TTF_Init+set}" = set; then
+	{ echo "$as_me:$LINENO: checking for library containing TTF_Init" >&5
+echo $ECHO_N "checking for library containing TTF_Init... $ECHO_C" >&6; }
+if test "${ac_cv_search_TTF_Init+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lSDL_ttf  $LIBS"
+  ac_func_search_save_LIBS=$LIBS
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -8537,7 +8597,14 @@ return TTF_Init ();
   return 0;
 }
 _ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
+for ac_lib in '' SDL_ttf; do
+  if test -z "$ac_lib"; then
+    ac_res="none required"
+  else
+    ac_res=-l$ac_lib
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+  fi
+  rm -f conftest.$ac_objext conftest$ac_exeext
 if { (ac_try="$ac_link"
 case "(($ac_try" in
   *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
@@ -8555,35 +8622,45 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_SDL_ttf_TTF_Init=yes
+  ac_cv_search_TTF_Init=$ac_res
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_SDL_ttf_TTF_Init=no
+
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
+      conftest$ac_exeext
+  if test "${ac_cv_search_TTF_Init+set}" = set; then
+  break
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_SDL_ttf_TTF_Init" >&5
-echo "${ECHO_T}$ac_cv_lib_SDL_ttf_TTF_Init" >&6; }
-if test $ac_cv_lib_SDL_ttf_TTF_Init = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBSDL_TTF 1
-_ACEOF
-
-  LIBS="-lSDL_ttf $LIBS"
-
+done
+if test "${ac_cv_search_TTF_Init+set}" = set; then
+  :
 else
-  { { echo "$as_me:$LINENO: error: You must have SDL_ttf!!!" >&5
-echo "$as_me: error: You must have SDL_ttf!!!" >&2;}
-   { (exit 1); exit 1; }; }
+  ac_cv_search_TTF_Init=no
+fi
+rm conftest.$ac_ext
+LIBS=$ac_func_search_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_search_TTF_Init" >&5
+echo "${ECHO_T}$ac_cv_search_TTF_Init" >&6; }
+ac_res=$ac_cv_search_TTF_Init
+if test "$ac_res" != no; then
+  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
+
 fi
 
+	if test "$ac_cv_search_TTF_Init" = "no"
+	then
+		{ { echo "$as_me:$LINENO: error: You must have the SDL_ttf development libraries" >&5
+echo "$as_me: error: You must have the SDL_ttf development libraries" >&2;}
+   { (exit 1); exit 1; }; }
+	fi
 
 	CPPFLAGS=$OLD_CPPFLAGS
+	CFLAGS=$OLD_CFLAGS
 	LDFLAGS=$OLD_LDFLAGS
 
 	#---------------------------------------------------------------------------------------------
