* Fixed fullscreen glx bug

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8440,18 +8440,153 @@ done
 
 	if test "$ac_cv_header_X11_extensions_xf86vmode_h" = "yes"
 	then
-		HAVE_VID_VIDMODE=1
+		echo "$as_me:$LINENO: checking for library containing XF86VidModeQueryVersion" >&5
+echo $ECHO_N "checking for library containing XF86VidModeQueryVersion... $ECHO_C" >&6
+if test "${ac_cv_search_XF86VidModeQueryVersion+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_func_search_save_LIBS=$LIBS
+ac_cv_search_XF86VidModeQueryVersion=no
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 
-		cat >>confdefs.h <<\_ACEOF
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char XF86VidModeQueryVersion ();
+int
+main ()
+{
+XF86VidModeQueryVersion ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_XF86VidModeQueryVersion="none required"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+if test "$ac_cv_search_XF86VidModeQueryVersion" = no; then
+  for ac_lib in Xxf86vm; do
+    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char XF86VidModeQueryVersion ();
+int
+main ()
+{
+XF86VidModeQueryVersion ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_search_XF86VidModeQueryVersion="-l$ac_lib"
+break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+  done
+fi
+LIBS=$ac_func_search_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_search_XF86VidModeQueryVersion" >&5
+echo "${ECHO_T}$ac_cv_search_XF86VidModeQueryVersion" >&6
+if test "$ac_cv_search_XF86VidModeQueryVersion" != no; then
+  test "$ac_cv_search_XF86VidModeQueryVersion" = "none required" || LIBS="$ac_cv_search_XF86VidModeQueryVersion $LIBS"
+
+fi
+
+		if test "$ac_cv_search_XF86VidModeQueryVersion" != "no"
+		then
+			HAVE_VID_VIDMODE=1
+
+			cat >>confdefs.h <<\_ACEOF
 #define HAVE_VIDMODE 1
 _ACEOF
 
+		elif test "$with_vid_vidmode" = "yes"
+		then
+			{ { echo "$as_me:$LINENO: error: --with-vidmode specified but couldn't find XF86VidModeQueryVersion" >&5
+echo "$as_me: error: --with-vidmode specified but couldn't find XF86VidModeQueryVersion" >&2;}
+   { (exit 1); exit 1; }; }
+		fi
 	elif test "$with_vid_vidmode" = "yes"
 	then
 		{ { echo "$as_me:$LINENO: error: --with-vidmode specified but couldn't find X11/extensions/xf86vmode.h" >&5
 echo "$as_me: error: --with-vidmode specified but couldn't find X11/extensions/xf86vmode.h" >&2;}
    { (exit 1); exit 1; }; }
 	fi
+
+
+
 fi
 
 
