* added support for PKGDATADIR and PKGLIBDIR via configure options

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -690,6 +690,7 @@ BUILD_UFO2MAP
 BUILD_DEBUG
 PARANOID
 PROFILING
+PKGDATADIR
 EXE_EXT
 CLIENT_LIBS
 CLIENT_CFLAGS
@@ -1733,12 +1734,8 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
-# check build/host/target systems
-# (build  = system we're building on,
-#  host   = system we're building for,
-#  target = system the program we're building will build for)
 ac_aux_dir=
-for ac_dir in "$srcdir" "$srcdir/.." "$srcdir/../.."; do
+for ac_dir in . "$srcdir"/.; do
   if test -f "$ac_dir/install-sh"; then
     ac_aux_dir=$ac_dir
     ac_install_sh="$ac_aux_dir/install-sh -c"
@@ -1754,8 +1751,8 @@ for ac_dir in "$srcdir" "$srcdir/.." "$srcdir/../.."; do
   fi
 done
 if test -z "$ac_aux_dir"; then
-  { { echo "$as_me:$LINENO: error: cannot find install-sh or install.sh in \"$srcdir\" \"$srcdir/..\" \"$srcdir/../..\"" >&5
-echo "$as_me: error: cannot find install-sh or install.sh in \"$srcdir\" \"$srcdir/..\" \"$srcdir/../..\"" >&2;}
+  { { echo "$as_me:$LINENO: error: cannot find install-sh or install.sh in . \"$srcdir\"/." >&5
+echo "$as_me: error: cannot find install-sh or install.sh in . \"$srcdir\"/." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -1768,6 +1765,11 @@ ac_config_sub="$SHELL $ac_aux_dir/config.sub"  # Please don't use this var.
 ac_configure="$SHELL $ac_aux_dir/configure"  # Please don't use this var.
 
 
+
+# check build/host/target systems
+# (build  = system we're building on,
+#  host   = system we're building for,
+#  target = system the program we're building will build for)
 # Make sure we can run config.sub.
 $SHELL "$ac_aux_dir/config.sub" sun4 >/dev/null 2>&1 ||
   { { echo "$as_me:$LINENO: error: cannot run $SHELL $ac_aux_dir/config.sub" >&5
@@ -9801,6 +9803,34 @@ else
 
 fi
 
+
+#---------------------------------------------------------------------------------------------
+# Fill in path variables
+#---------------------------------------------------------------------------------------------
+
+test "$prefix" = "NONE" && prefix=/usr/local
+test "$exec_prefix" = "NONE" && exec_prefix=$prefix
+
+eval PKGLIBDIR="$libdir/ufoai"
+
+cat >>confdefs.h <<_ACEOF
+#define PKGLIBDIR "$PKGLIBDIR"
+_ACEOF
+
+
+datarootdir=$prefix/share
+test "$datadir" = "NONE" && datadir=$datarootdir
+
+eval PKGDATADIR="$datadir/ufoai"
+
+cat >>confdefs.h <<_ACEOF
+#define PKGDATADIR "$PKGDATADIR"
+_ACEOF
+
+
+
+eval BINDIR="$bindir"
+
 #---------------------------------------------------------------------------------------------
 
 EXE_EXT="$ac_exe_ext"
@@ -10519,6 +10549,7 @@ BUILD_UFO2MAP!$BUILD_UFO2MAP$ac_delim
 BUILD_DEBUG!$BUILD_DEBUG$ac_delim
 PARANOID!$PARANOID$ac_delim
 PROFILING!$PROFILING$ac_delim
+PKGDATADIR!$PKGDATADIR$ac_delim
 EXE_EXT!$EXE_EXT$ac_delim
 CLIENT_LIBS!$CLIENT_LIBS$ac_delim
 CLIENT_CFLAGS!$CLIENT_CFLAGS$ac_delim
@@ -10530,7 +10561,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 86; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 87; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
