* removed alut

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6236,7 +6236,6 @@ WINDRES=$WINDRES
 # CHECK winsock2
 #---------------------------------------------------------------------------------------------
 
-WINDRES=""
 if test $TARGET_OS = "mingw32"
 then
 	{ echo "$as_me:$LINENO: result: Mingw32 - Trying to use Winsock2 (WS2_32)" >&5
@@ -6445,8 +6444,8 @@ _ACEOF
   LIBS="-lws2_32 $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: Winsock2 is needed for a Win32 build." >&5
-echo "$as_me: error: Winsock2 is needed for a Win32 build." >&2;}
+  { { echo "$as_me:$LINENO: error: Winsock2 is needed for a Win32 mingw build." >&5
+echo "$as_me: error: Winsock2 is needed for a Win32 mingw build." >&2;}
    { (exit 1); exit 1; }; }
 fi
 
@@ -8090,96 +8089,6 @@ fi
 		then
 			{ echo "$as_me:$LINENO: WARNING: couldn't find OpenAL library!" >&5
 echo "$as_me: WARNING: couldn't find OpenAL library!" >&2;}
-			HAVE_OPENAL=0
-
-		fi
-		{ echo "$as_me:$LINENO: checking for library containing alutLoadWAVFile" >&5
-echo $ECHO_N "checking for library containing alutLoadWAVFile... $ECHO_C" >&6; }
-if test "${ac_cv_search_alutLoadWAVFile+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_func_search_save_LIBS=$LIBS
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any GCC internal prototype to avoid an error.
-   Use char because int might match the return type of a GCC
-   builtin and then its argument prototype would still apply.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-char alutLoadWAVFile ();
-int
-main ()
-{
-return alutLoadWAVFile ();
-  ;
-  return 0;
-}
-_ACEOF
-for ac_lib in '' alut; do
-  if test -z "$ac_lib"; then
-    ac_res="none required"
-  else
-    ac_res=-l$ac_lib
-    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
-  fi
-  rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  ac_cv_search_alutLoadWAVFile=$ac_res
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext
-  if test "${ac_cv_search_alutLoadWAVFile+set}" = set; then
-  break
-fi
-done
-if test "${ac_cv_search_alutLoadWAVFile+set}" = set; then
-  :
-else
-  ac_cv_search_alutLoadWAVFile=no
-fi
-rm conftest.$ac_ext
-LIBS=$ac_func_search_save_LIBS
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_search_alutLoadWAVFile" >&5
-echo "${ECHO_T}$ac_cv_search_alutLoadWAVFile" >&6; }
-ac_res=$ac_cv_search_alutLoadWAVFile
-if test "$ac_res" != no; then
-  test "$ac_res" = "none required" || LIBS="$ac_res $LIBS"
-
-fi
-
-		if test "$ac_cv_search_alutLoadWAVFile" = "no"
-		then
-			{ echo "$as_me:$LINENO: WARNING: couldn't find OpenAL utility library!" >&5
-echo "$as_me: WARNING: couldn't find OpenAL utility library!" >&2;}
 			HAVE_OPENAL=0
 
 		fi
