* introduced one static popupText array (use this instead of several other static char arrays) * fixed MN_Popup calls with none static char arrays * extended error messages for save function

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -700,6 +700,7 @@ PROFILING
 EXE_EXT
 REF_GL_LIBS
 REF_GLX_LIBS
+REF_GLX_CFLAGS
 REF_SDL_LIBS
 CLIENT_LIBS
 SERVER_LIBS
@@ -8539,6 +8540,116 @@ echo "$as_me: WARNING: found GLX headers but couldn't find GLX libraries, GLX wi
 echo "$as_me: error: --with-vid-glx specified but failed find GLX header" >&2;}
    { (exit 1); exit 1; }; }
 	fi
+
+for ac_func in XDGAQueryVersion
+do
+as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
+{ echo "$as_me:$LINENO: checking for $ac_func" >&5
+echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6; }
+if { as_var=$as_ac_var; eval "test \"\${$as_var+set}\" = set"; }; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+/* Define $ac_func to an innocuous variant, in case <limits.h> declares $ac_func.
+   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
+#define $ac_func innocuous_$ac_func
+
+/* System header to define __stub macros and hopefully few prototypes,
+    which can conflict with char $ac_func (); below.
+    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
+    <limits.h> exists even on freestanding compilers.  */
+
+#ifdef __STDC__
+# include <limits.h>
+#else
+# include <assert.h>
+#endif
+
+#undef $ac_func
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char $ac_func ();
+/* The GNU C library defines this for functions which it implements
+    to always fail with ENOSYS.  Some functions are actually named
+    something starting with __ and the normal name is an alias.  */
+#if defined __stub_$ac_func || defined __stub___$ac_func
+choke me
+#endif
+
+int
+main ()
+{
+return $ac_func ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag" || test ! -s conftest.err'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  eval "$as_ac_var=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	eval "$as_ac_var=no"
+fi
+
+rm -f core conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+ac_res=`eval echo '${'$as_ac_var'}'`
+	       { echo "$as_me:$LINENO: result: $ac_res" >&5
+echo "${ECHO_T}$ac_res" >&6; }
+if test `eval echo '${'$as_ac_var'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
+_ACEOF
+ REF_GLX_CFLAGS="$REF_GLX_CFLAGS -DXF86DGAQueryVersion=XDGAQueryVersion"
+fi
+done
+
 else
 	{ echo "$as_me:$LINENO: Without GLX" >&5
 echo "$as_me: Without GLX" >&6;}
@@ -11037,6 +11148,8 @@ REF_GL_LIBS="$REF_GL_LIBS"
 
 REF_GLX_LIBS="$REF_GLX_LIBS"
 
+REF_GLX_CFLAGS="$REF_GLX_CFLAGS"
+
 REF_SDL_LIBS="$REF_SDL_LIBS"
 
 CLIENT_LIBS="$CLIENT_LIBS"
@@ -11816,6 +11929,7 @@ PROFILING!$PROFILING$ac_delim
 EXE_EXT!$EXE_EXT$ac_delim
 REF_GL_LIBS!$REF_GL_LIBS$ac_delim
 REF_GLX_LIBS!$REF_GLX_LIBS$ac_delim
+REF_GLX_CFLAGS!$REF_GLX_CFLAGS$ac_delim
 REF_SDL_LIBS!$REF_SDL_LIBS$ac_delim
 CLIENT_LIBS!$CLIENT_LIBS$ac_delim
 SERVER_LIBS!$SERVER_LIBS$ac_delim
@@ -11832,7 +11946,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 19; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 20; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
