* add SSE option for x86 CPUs --enable-sse *   nearly useless for ufo and radiant *   but very useful for ufo2map

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24,6 +24,7 @@ CXX=
 USE_CCACHE=
 STATIC=
 W2K=
+SSE=
 
 HOST_OS=`uname | sed -e s/_.*// | tr '[:upper:]' '[:lower:]'`
 TARGET_OS=${HOST_OS}
@@ -111,6 +112,7 @@ makefile_local() {
 	add_to_makefile_local PROFILING "Enable profiling"
 	add_to_makefile_local STATIC "Enable static linking"
 	add_to_makefile_local W2K "Enable Windows 2000 compatibility"
+	add_to_makefile_local SSE "Enable Streaming SIMD Extensions"
 	add_to_makefile_local HARD_LINKED_GAME
 	add_to_makefile_local UNIVERSAL "Build a universal binary"
 	add_to_makefile_local TARGET_OS "Compile for ${TARGET_OS}"
@@ -184,6 +186,9 @@ usage() {
 	echo " --enable-static          enable static linking"
 	echo " --enable-universal       enable universal build"
 	echo " --enable-w2k             enable Windows 2000 compatibility"
+   if [ -n "$(echo ${TARGET_ARCH} | grep -e '^i.86$' -e '^x86_64$')" ]; then
+	echo " --enable-sse             enable Streaming SIMD Extensions"
+   fi
 	echo " --disable-execinfo       disable backtraces for crashes"
 	echo " --disable-signals        disable the use of a signal handler"
 	echo
@@ -347,6 +352,15 @@ while [ $# -gt 0 ]; do
 		W2K=1
 		;;
 	--disable-w2k)
+		;;
+	--enable-sse)
+		if [ -z "$(echo ${TARGET_ARCH} | grep -e '^i.86$' -e '^x86_64$')" ] ;then
+			echo "invalid $1 option for your CPU"
+			exit 1
+		fi
+		SSE=1
+		;;
+	--disable-sse)
 		;;
 	--enable-signals)
 		;;
